### ISSUE TITLE
学长可否联系你一下，报了Lu老师组

### ISSUE THREAD

**Issue by lizhiyuanqwe** [MaybeJT/chaojing_demo#2]
可以留一下您的联系方式吗，我今年考研报的这个组，想请教一下
我的邮箱562309285@qq.com

**Comment by MaybeJT** [comment]
QQ1317239583

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："lizhiyuanqwe "<notifications@github.com&gt;;
发送时间：2020年1月5日(星期天) 下午4:05
收件人："MaybeJT/chaojing_demo" <chaojing_demo@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[MaybeJT/chaojing_demo] 学长可否联系你一下，报了Lu老师组 (#2)
-----------------------------------

 
可以留一下您的联系方式吗，我今年考研报的这个组，想请教一下
 我的邮箱562309285@qq.com
